name: uapatron build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2.1.7
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          m2-
    - uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: '1.10.3.1087'
    - name: Build uberjar
      run: make uber
    - name: "Get tag"
      run: echo "RELEASE_TAG=$(cat target/classes/VERSION)" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/uapatron-*.jar
        tag_name: ${{ env.RELEASE_TAG }}
