name: uapatron build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2.1.7
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          m2-
    - uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: '1.10.3.1087'
    - run: make uber
    - name: "Generate tag"
      run: |
        COMMIT_DATE=$(git show -s --format=%cd --date=format:%y%m%d-%H%M HEAD)
        echo "RELEASE_TAG=${COMMIT_DATE}" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/uapatron.jar
        tag_name: ${{ env.RELEASE_TAG }}
